2025-05-29 23:06:28,575 INFO    Thread-19 (_run_job):137397 [wandb_setup.py:_flush():70] Current SDK version is 0.19.11
2025-05-29 23:06:28,575 INFO    Thread-19 (_run_job):137397 [wandb_setup.py:_flush():70] Configure stats pid to 137397
2025-05-29 23:06:28,575 INFO    Thread-19 (_run_job):137397 [wandb_setup.py:_flush():70] Loading settings from /nfs/homes/sdreyer/.config/wandb/settings
2025-05-29 23:06:28,576 INFO    Thread-19 (_run_job):137397 [wandb_setup.py:_flush():70] Loading settings from /nfs/homes/sdreyer/Digit-Classification-Pytorch/wandb/settings
2025-05-29 23:06:28,576 INFO    Thread-19 (_run_job):137397 [wandb_setup.py:_flush():70] Loading settings from environment variables
2025-05-29 23:06:28,576 INFO    Thread-19 (_run_job):137397 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /nfs/homes/sdreyer/Digit-Classification-Pytorch/wandb/run-20250529_230628-clvtg0qv/logs/debug.log
2025-05-29 23:06:28,576 INFO    Thread-19 (_run_job):137397 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /nfs/homes/sdreyer/Digit-Classification-Pytorch/wandb/run-20250529_230628-clvtg0qv/logs/debug-internal.log
2025-05-29 23:06:28,577 INFO    Thread-19 (_run_job):137397 [wandb_init.py:init():852] calling init triggers
2025-05-29 23:06:28,577 INFO    Thread-19 (_run_job):137397 [wandb_init.py:init():857] wandb.init called with sweep_config: {'batch_size': 128, 'dropout': 0.55, 'epochs': 1000, 'learning_rate': 0.005, 'optimizer': 'Adam', 'train_samples': 1702}
config: {'_wandb': {}}
2025-05-29 23:06:28,577 INFO    Thread-19 (_run_job):137397 [wandb_init.py:init():893] starting backend
2025-05-29 23:06:28,578 INFO    Thread-19 (_run_job):137397 [wandb_init.py:init():897] sending inform_init request
2025-05-29 23:06:28,579 INFO    Thread-19 (_run_job):137397 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-29 23:06:28,579 INFO    Thread-19 (_run_job):137397 [wandb_init.py:init():907] backend started and connected
2025-05-29 23:06:28,580 INFO    Thread-19 (_run_job):137397 [wandb_run.py:_config_callback():1436] config_cb None None {'batch_size': 128, 'dropout': 0.55, 'epochs': 1000, 'learning_rate': 0.005, 'optimizer': 'Adam', 'train_samples': 1702}
2025-05-29 23:06:28,581 INFO    Thread-19 (_run_job):137397 [wandb_init.py:init():1005] updated telemetry
2025-05-29 23:06:28,591 INFO    Thread-19 (_run_job):137397 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-05-29 23:06:29,029 INFO    Thread-19 (_run_job):137397 [wandb_init.py:init():1104] starting run threads in backend
2025-05-29 23:06:29,195 INFO    Thread-19 (_run_job):137397 [wandb_run.py:_console_start():2573] atexit reg
2025-05-29 23:06:29,196 INFO    Thread-19 (_run_job):137397 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-05-29 23:06:29,196 INFO    Thread-19 (_run_job):137397 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-05-29 23:06:29,196 INFO    Thread-19 (_run_job):137397 [wandb_run.py:_redirect():2513] Redirects installed.
2025-05-29 23:06:29,197 INFO    Thread-19 (_run_job):137397 [wandb_init.py:init():1150] run started, returning control to user process
2025-05-29 23:09:31,642 INFO    Thread-19 (_run_job):137397 [retry.py:__call__():175] Retry attempt failed:
Traceback (most recent call last):
  File "/nfs/homes/sdreyer/.local/lib/python3.12/site-packages/wandb/sdk/lib/retry.py", line 134, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/homes/sdreyer/.local/lib/python3.12/site-packages/wandb/apis/public/api.py", line 108, in execute
    return self._client.execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/homes/sdreyer/.local/lib/python3.12/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/homes/sdreyer/.local/lib/python3.12/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/homes/sdreyer/.local/lib/python3.12/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/nfs/homes/sdreyer/.local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql
2025-05-29 23:09:36,564 ERROR   Thread-3 (_heartbeat):137397 [internal_api.py:execute():402] [no run ID] 500 response executing GraphQL.
2025-05-29 23:09:36,564 ERROR   Thread-3 (_heartbeat):137397 [internal_api.py:execute():403] [no run ID] {"errors":[{"message":"context deadline exceeded"}]}
2025-05-29 23:11:35,797 INFO    Thread-19 (_run_job):137397 [wandb_run.py:_finish():2321] finishing run svenja-dreyer-tu-dortmund/Messungen-noTu-Tu/clvtg0qv
2025-05-29 23:11:35,798 INFO    Thread-19 (_run_job):137397 [wandb_run.py:_atexit_cleanup():2538] got exitcode: 0
2025-05-29 23:11:35,798 INFO    Thread-19 (_run_job):137397 [wandb_run.py:_restore():2520] restore
2025-05-29 23:11:35,799 INFO    Thread-19 (_run_job):137397 [wandb_run.py:_restore():2526] restore done
2025-05-29 23:11:39,228 INFO    Thread-19 (_run_job):137397 [wandb_run.py:_footer_history_summary_info():4188] rendering history
2025-05-29 23:11:39,229 INFO    Thread-19 (_run_job):137397 [wandb_run.py:_footer_history_summary_info():4220] rendering summary
2025-05-29 23:11:39,230 INFO    Thread-19 (_run_job):137397 [wandb_run.py:_footer_sync_info():4149] logging synced files
